/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneymanagement.View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import moneymanagement.Controller.UsersController;
import moneymanagement.Exception.UsersException;

/**
 *
 * @author zulfa
 */
public class Register extends javax.swing.JFrame {
    UsersController usersController;
    /**
     * Creates new form Register
     */
    public Register() {
        usersController = new UsersController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginPanel_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        goToSignin = new javax.swing.JButton();
        loginPanel_kanan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        registerUsername = new javax.swing.JTextField();
        registerPassword = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        registerEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        registerName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel_kiri.setBackground(new java.awt.Color(58, 194, 178));
        loginPanel_kiri.setPreferredSize(new java.awt.Dimension(640, 720));
        loginPanel_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hallo!");
        loginPanel_kiri.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Untuk selalu terhubung dengan kami");
        loginPanel_kiri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("login menggunakan akun anda");
        loginPanel_kiri.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sudah memiliki akun?");
        loginPanel_kiri.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));

        goToSignin.setBackground(new java.awt.Color(255, 255, 255));
        goToSignin.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        goToSignin.setForeground(new java.awt.Color(61, 146, 136));
        goToSignin.setText("Sign In");
        goToSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSigninActionPerformed(evt);
            }
        });
        loginPanel_kiri.add(goToSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 210, 40));

        loginPanel.add(loginPanel_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginPanel_kanan.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel_kanan.setPreferredSize(new java.awt.Dimension(640, 720));
        loginPanel_kanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 37)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 194, 178));
        jLabel8.setText("Register");
        loginPanel_kanan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        registerUsername.setBackground(new java.awt.Color(217, 217, 217));
        registerUsername.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        loginPanel_kanan.add(registerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 380, 50));

        registerPassword.setBackground(new java.awt.Color(217, 217, 217));
        registerPassword.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        registerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPasswordActionPerformed(evt);
            }
        });
        loginPanel_kanan.add(registerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 380, 50));

        registerButton.setBackground(new java.awt.Color(58, 194, 178));
        registerButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        loginPanel_kanan.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 380, 50));

        registerEmail.setBackground(new java.awt.Color(217, 217, 217));
        registerEmail.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        registerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmailActionPerformed(evt);
            }
        });
        loginPanel_kanan.add(registerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 380, 50));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(58, 194, 178));
        jLabel5.setText("Username");
        loginPanel_kanan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(58, 194, 178));
        jLabel6.setText("Email");
        loginPanel_kanan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(58, 194, 178));
        jLabel7.setText("Password");
        loginPanel_kanan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(58, 194, 178));
        jLabel9.setText("Name");
        loginPanel_kanan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        registerName.setBackground(new java.awt.Color(217, 217, 217));
        registerName.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        loginPanel_kanan.add(registerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 380, 50));

        loginPanel.add(loginPanel_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSigninActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToSigninActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerEmailActionPerformed

    public JTextField getRegisterEmail() {
        return registerEmail;
    }

    public JTextField getRegisterPassword() {
        return registerPassword;
    }

    public JTextField getRegisterUsername() {
        return registerUsername;
    }

    public JTextField getRegisterName() {
        return registerName;
    }

    private void registerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPasswordActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        try {
            usersController.tambahUser(this);
        } catch (SQLException | UsersException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goToSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel loginPanel_kanan;
    private javax.swing.JPanel loginPanel_kiri;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JTextField registerName;
    private javax.swing.JTextField registerPassword;
    private javax.swing.JTextField registerUsername;
    // End of variables declaration//GEN-END:variables
}
