/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneymanagement.View.Panel;

/**
 *
 * @author Hp
 */
public class AboutView extends javax.swing.JPanel {

    /**
     * Creates new form AboutView
     */
    public AboutView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelNama2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        PanelNama3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PanelNama6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PanelNama7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        PanelNama8 = new javax.swing.JPanel();
        PanelNama9 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 157, 145));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(66, 157, 145));
        jPanel2.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 690, -1, -1));

        jPanel3.setBackground(new java.awt.Color(66, 157, 145));
        jPanel3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        jPanel4.setBackground(new java.awt.Color(66, 157, 145));
        jPanel4.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Foto/tijar.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 140, 170));

        PanelNama2.setBackground(new java.awt.Color(53, 215, 185));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Zulfi Fadilah Azhar");

        javax.swing.GroupLayout PanelNama2Layout = new javax.swing.GroupLayout(PanelNama2);
        PanelNama2.setLayout(PanelNama2Layout);
        PanelNama2Layout.setHorizontalGroup(
            PanelNama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNama2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelNama2Layout.setVerticalGroup(
            PanelNama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNama2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(PanelNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 220, 20));

        PanelNama3.setBackground(new java.awt.Color(53, 215, 185));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Tanisa Auliyani");

        javax.swing.GroupLayout PanelNama3Layout = new javax.swing.GroupLayout(PanelNama3);
        PanelNama3.setLayout(PanelNama3Layout);
        PanelNama3Layout.setHorizontalGroup(
            PanelNama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNama3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelNama3Layout.setVerticalGroup(
            PanelNama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNama3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(PanelNama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 220, 20));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel4.setText("- Implementasi Konsep MVC");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 240, -1));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel10.setText("10122005");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 220, -1));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel12.setText("10122019");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 220, -1));

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel15.setText("Kontribusi 100%");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 220, -1));

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel17.setText("Kontribusi 100%");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 220, -1));

        PanelNama6.setBackground(new java.awt.Color(53, 215, 185));

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(" Tijar Taufik");

        javax.swing.GroupLayout PanelNama6Layout = new javax.swing.GroupLayout(PanelNama6);
        PanelNama6.setLayout(PanelNama6Layout);
        PanelNama6Layout.setHorizontalGroup(
            PanelNama6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNama6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelNama6Layout.setVerticalGroup(
            PanelNama6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNama6Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(PanelNama6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 220, 20));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Foto/zulfi.jpg"))); // NOI18N
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 140, 170));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Foto/tanisa.jpg"))); // NOI18N
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 170));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel13.setText("10122021");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 220, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Foto/bambang.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 170, Short.MAX_VALUE)
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 140, 170));

        jLabel30.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel30.setText("Kontribusi 100%");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 220, -1));

        PanelNama7.setBackground(new java.awt.Color(53, 215, 185));

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(" Bambang Firman");

        javax.swing.GroupLayout PanelNama7Layout = new javax.swing.GroupLayout(PanelNama7);
        PanelNama7.setLayout(PanelNama7Layout);
        PanelNama7Layout.setHorizontalGroup(
            PanelNama7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNama7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelNama7Layout.setVerticalGroup(
            PanelNama7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNama7Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(PanelNama7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 220, 20));

        jLabel33.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel33.setText("10122027");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 220, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Foto/umam.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel34)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 170, Short.MAX_VALUE)
        );

        add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 140, 170));

        jLabel35.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel35.setText("Kontribusi 100%");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 220, -1));

        PanelNama8.setBackground(new java.awt.Color(53, 215, 185));

        PanelNama9.setBackground(new java.awt.Color(53, 215, 185));

        jLabel39.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(" Khotibul Umam");

        javax.swing.GroupLayout PanelNama9Layout = new javax.swing.GroupLayout(PanelNama9);
        PanelNama9.setLayout(PanelNama9Layout);
        PanelNama9Layout.setHorizontalGroup(
            PanelNama9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNama9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelNama9Layout.setVerticalGroup(
            PanelNama9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNama9Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelNama8Layout = new javax.swing.GroupLayout(PanelNama8);
        PanelNama8.setLayout(PanelNama8Layout);
        PanelNama8Layout.setHorizontalGroup(
            PanelNama8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(PanelNama8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelNama8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelNama9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelNama8Layout.setVerticalGroup(
            PanelNama8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(PanelNama8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelNama8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelNama9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(PanelNama8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 220, 20));

        jLabel38.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel38.setText("10122036");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/about -title.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel5.setText("Kontribusi 100%");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 220, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel7.setText("- Slicing UI Login & Register View");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 270, -1));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel11.setText("- CRUD Database");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 240, -1));

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel14.setText("- Sistem Login & Register");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 240, -1));

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel18.setText("- Implementasi Dynamic Panel");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 250, -1));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel19.setText("- Slicing UI Navbar View");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 240, -1));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel20.setText("- UI/UX Designer");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 240, -1));

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel21.setText("- Implementasi Calendar");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 240, -1));

        jLabel22.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel22.setText("- Membuat Pie Chart");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 240, -1));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel24.setText("- Slicing UI Transaksi Form");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 240, -1));

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel25.setText("- Slicing UI Transaksi View");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 240, -1));

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel28.setText("- Fitur Tanggal dan Jam Realtime");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 270, -1));

        jLabel31.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel31.setText("- Slicing UI Saldo View");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 240, -1));

        jLabel36.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel36.setText("- Slicing UI Dashboard View");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 240, -1));

        jLabel40.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel40.setText("- Dummy Data Untuk Diagram");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 240, -1));

        jLabel41.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel41.setText("- Membuat Diagram Batang");
        add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 240, -1));

        jLabel42.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel42.setText("- Slicing UI Statistik View");
        add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 240, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 215, 185));
        jLabel3.setText("KELOMPOK 3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNama2;
    private javax.swing.JPanel PanelNama3;
    private javax.swing.JPanel PanelNama6;
    private javax.swing.JPanel PanelNama7;
    private javax.swing.JPanel PanelNama8;
    private javax.swing.JPanel PanelNama9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
