package moneymanagement.View.Panel;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class SaldoView extends javax.swing.JPanel {

    /**
     * Creates new form SaldoView
     */
    public SaldoView() {
        initComponents();
    }

    public JLabel getPemasukanSaldo() {
        return pemasukanSaldo;
    }

    public void setPemasukanSaldo(JLabel pemasukanSaldo) {
        this.pemasukanSaldo = pemasukanSaldo;
    }

    public JLabel getPengeluaranSaldo() {
        return pengeluaranSaldo;
    }

    public void setPengeluaranSaldo(JLabel pengeluaranSaldo) {
        this.pengeluaranSaldo = pengeluaranSaldo;
    }

    public JLabel getTotalSaldoSaldo() {
        return totalSaldoSaldo;
    }

    public void setTotalSaldoSaldo(JLabel totalSaldoSaldo) {
        this.totalSaldoSaldo = totalSaldoSaldo;
    }
    
    public JLabel getCashSaldo() {
        return cashSaldo;
    }

    public void setCashSaldo(JLabel cashSaldo) {
        this.cashSaldo = cashSaldo;
    }

    public JLabel getDebitBca() {
        return debitBca;
    }

    public void setDebitBca(JLabel debitBca) {
        this.debitBca = debitBca;
    }

    public JLabel getDebitBri() {
        return debitBri;
    }

    public void setDebitBri(JLabel debitBri) {
        this.debitBri = debitBri;
    }

    public JLabel getGopaySaldo() {
        return gopaySaldo;
    }

    public void setGopaySaldo(JLabel gopaySaldo) {
        this.gopaySaldo = gopaySaldo;
    }

    public JLabel getOvoSaldo() {
        return ovoSaldo;
    }

    public void setOvoSaldo(JLabel ovoSaldo) {
        this.ovoSaldo = ovoSaldo;
    }

    public JLabel getSpaySaldo() {
        return spaySaldo;
    }

    public void setSpaySaldo(JLabel spaySaldo) {
        this.spaySaldo = spaySaldo;
    }

    public void setPemasukanLabel(int pemasukan) {
        pemasukanSaldo.setText(Integer.toString(pemasukan));
    }

    public void setPengeluaranLabel(int pengeluaran) {
        pengeluaranSaldo.setText(Integer.toString(pengeluaran));
    }

    public void setTotalSaldoLabel(int totalSaldo) {
        totalSaldoSaldo.setText(Integer.toString(totalSaldo));
    }
    
    public void setCashSaldoLabel(int cash){
        cashSaldo.setText(Integer.toString(cash));
    }
    
    public void setGopayLabel(int gopay){
        gopaySaldo.setText(Integer.toString(gopay));
    }
    public void setOvoLabel(int ovo){
        ovoSaldo.setText(Integer.toString(ovo));
    }
    public void setSpayLabel(int spay){
        spaySaldo.setText(Integer.toString(spay));
    }
    public void setBriLabel(int bri){
        debitBri.setText(Integer.toString(bri));
    }
    public void setBcaLabel(int bca){
        debitBca.setText(Integer.toString(bca));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pengeluaranSaldo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        ovoSaldo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        spaySaldo = new javax.swing.JLabel();
        gopaySaldo = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        pemasukanSaldo = new javax.swing.JLabel();
        inputTransaksi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        totalSaldoSaldo = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        cashSaldo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        debitBca = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        debitBri = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 157, 145));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(66, 157, 145));
        jPanel2.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(66, 157, 145));
        jPanel3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        jPanel4.setBackground(new java.awt.Color(66, 157, 145));
        jPanel4.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 690, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/saldo-title.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 194, 178)));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(66, 157, 145));
        jPanel6.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 114, 104));
        jLabel2.setText("Pengeluaran");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(58, 194, 178));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 10));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel3.setText("Rp");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        pengeluaranSaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        pengeluaranSaldo.setText("0");
        jPanel5.add(pengeluaranSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 280, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 194, 178)));
        jPanel7.setPreferredSize(new java.awt.Dimension(280, 280));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(66, 157, 145));
        jPanel8.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 114, 104));
        jLabel4.setText("Saldo E-Money");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(58, 194, 178));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 10));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel5.setText("Rp");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/spay.png"))); // NOI18N
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(58, 194, 178));
        jPanel7.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 10));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/gopay.png"))); // NOI18N
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/ovo.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(58, 194, 178));
        jPanel7.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 10));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel16.setText("Rp");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        ovoSaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        ovoSaldo.setText("0");
        jPanel7.add(ovoSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, -1));

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel17.setText("Rp");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        spaySaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        spaySaldo.setText("0");
        jPanel7.add(spaySaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, -1));

        gopaySaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        gopaySaldo.setText("0");
        jPanel7.add(gopaySaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 194, 178)));
        jPanel9.setPreferredSize(new java.awt.Dimension(280, 100));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(66, 157, 145));
        jPanel10.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 114, 104));
        jLabel6.setText("Pemasukan");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(58, 194, 178));
        jPanel9.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 10));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel7.setText("Rp");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        pemasukanSaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        pemasukanSaldo.setText("0");
        jPanel9.add(pemasukanSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        inputTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        inputTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputTransaksiMouseClicked(evt);
            }
        });
        inputTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/input.png"))); // NOI18N
        inputTransaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        add(inputTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 194, 178)));
        jPanel11.setPreferredSize(new java.awt.Dimension(280, 100));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(66, 157, 145));
        jPanel12.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 114, 104));
        jLabel9.setText("Total Saldo");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(58, 194, 178));
        jPanel11.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 10));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel10.setText("Rp");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        totalSaldoSaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        totalSaldoSaldo.setText("0");
        jPanel11.add(totalSaldoSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, -1));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 194, 178)));
        jPanel13.setPreferredSize(new java.awt.Dimension(280, 100));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(66, 157, 145));
        jPanel14.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 114, 104));
        jLabel11.setText("Saldo Cash");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(58, 194, 178));
        jPanel13.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 10));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel12.setText("Rp");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cashSaldo.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        cashSaldo.setText("0");
        jPanel13.add(cashSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, -1));

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel18.setText("BCA");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(58, 194, 178));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 560, 10));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/bca.png"))); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moneymanagement/Assets/Icon/bri.png"))); // NOI18N
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(58, 194, 178));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 270, 10));

        jSeparator10.setForeground(new java.awt.Color(58, 194, 178));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 560, 10));

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(37, 114, 104));
        jLabel21.setText("Saldo Debit");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel22.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(37, 114, 104));
        jLabel22.setText("Debit Card");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(37, 114, 104));
        jLabel23.setText("Debit Card");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel24.setText("Rp");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel25.setText("BRI");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        debitBca.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        debitBca.setText("0");
        add(debitBca, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, -1, -1));

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel27.setText("Rp");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        debitBri.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        debitBri.setText("0");
        add(debitBri, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void inputTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTransaksiMouseClicked
        // Buat instance dari JDialog
        JDialog transaksiDialog = new JDialog((Frame) SwingUtilities.getWindowAncestor(this), "Transaksi Form", true);

        // Set konten dari JDialog dengan TransaksiForm
        TransaksiForm transaksiForm = new TransaksiForm();
        transaksiDialog.getContentPane().add(transaksiForm);
        transaksiDialog.pack();
        transaksiDialog.setVisible(true);
    }//GEN-LAST:event_inputTransaksiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashSaldo;
    private javax.swing.JLabel debitBca;
    private javax.swing.JLabel debitBri;
    private javax.swing.JLabel gopaySaldo;
    private javax.swing.JPanel inputTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel ovoSaldo;
    private javax.swing.JLabel pemasukanSaldo;
    private javax.swing.JLabel pengeluaranSaldo;
    private javax.swing.JLabel spaySaldo;
    private javax.swing.JLabel totalSaldoSaldo;
    // End of variables declaration//GEN-END:variables
}
