package moneymanagement.View.Panel;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JButton;
import moneymanagement.Controller.Transaksi.TransaksiController;
import moneymanagement.Model.Transaksi.TransaksiModel;

public class TransaksiForm extends javax.swing.JPanel {
    /** Creates new form TransaksiForm */
    public TransaksiForm() {
        initComponents();
        
    }

    public String getJenisTransaksi() {
        return (String) jenisTransaksi.getSelectedItem();
    }

    public String getCatatanTransaksi() {
        return catatanTransaksi.getText();
    }

    public String getAkunTransaksi() {
        return (String) akunTransaksi.getSelectedItem();
    }

    public String getKategoriTransaksi() {
        return (String) kategoriTransaksi.getSelectedItem();
    }

    public double getJumlahTransaksi() {
        return Double.parseDouble(jumlahTransaksi.getText());
    }

    public JButton getKirimButton() {
        return kirimButton;
    }

    public void setKirimButton(JButton kirimButton) {
        this.kirimButton = kirimButton;
    }

    public JDateChooser getTanggalTransaksi() {
        return tanggalTransaksi;
    }

    public void setTanggalTransaksi(JDateChooser tanggalTransaksi) {
        this.tanggalTransaksi = tanggalTransaksi;
    }
    

    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jumlahTransaksi = new javax.swing.JTextField();
        catatanTransaksi = new javax.swing.JTextField();
        akunTransaksi = new javax.swing.JComboBox<>();
        kategoriTransaksi = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        kirimButton = new javax.swing.JButton();
        jenisTransaksi = new javax.swing.JComboBox<>();
        jenisAkun = new javax.swing.JComboBox<>();
        tanggalTransaksi = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(500, 600));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 114, 104));
        jLabel1.setText("Transaksi");
        topPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(58, 194, 178));
        topPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 157, 145));
        jLabel2.setText("Jenis Transaksi");
        topPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 157, 145));
        jLabel3.setText("Catatan");
        topPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 157, 145));
        jLabel4.setText("Tanggal");
        topPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 157, 145));
        jLabel5.setText("Akun");
        topPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 157, 145));
        jLabel6.setText("Kategori");
        topPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(53, 157, 145));
        jLabel7.setText("Jumlah");
        topPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));
        topPanel.add(jumlahTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 150, 40));
        topPanel.add(catatanTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 150, 40));

        akunTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cash", "debit", "emoney" }));
        akunTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunTransaksiActionPerformed(evt);
            }
        });
        topPanel.add(akunTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 40));

        kategoriTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bulanan", "bonus", "thr" }));
        kategoriTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriTransaksiActionPerformed(evt);
            }
        });
        topPanel.add(kategoriTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, 40));

        jButton1.setBackground(new java.awt.Color(53, 157, 145));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        topPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 150, 50));

        kirimButton.setBackground(new java.awt.Color(53, 157, 145));
        kirimButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        kirimButton.setForeground(new java.awt.Color(255, 255, 255));
        kirimButton.setText("Simpan");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });
        topPanel.add(kirimButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 150, 50));

        jenisTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pemasukan", "pengeluaran" }));
        jenisTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisTransaksiActionPerformed(evt);
            }
        });
        topPanel.add(jenisTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        jenisAkun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        topPanel.add(jenisAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 40));

        tanggalTransaksi.setBackground(new java.awt.Color(58, 194, 178));
        tanggalTransaksi.setForeground(new java.awt.Color(35, 114, 104));
        topPanel.add(tanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, 40));

        add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        JDateChooser tanggalChooser = getTanggalTransaksi();
        Date selectedDate = tanggalChooser.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        String selectedJenisTransaksi = (String) jenisTransaksi.getSelectedItem();
        String tanggal = dateFormat.format(selectedDate);
        String akun = (String) akunTransaksi.getSelectedItem();
        String jenis = (String) jenisAkun.getSelectedItem();
        String kategori = (String) kategoriTransaksi.getSelectedItem();
        double jumlah = Double.parseDouble(jumlahTransaksi.getText());
        String catatan = catatanTransaksi.getText();

        TransaksiController transaksiController = new TransaksiController(new TransaksiModel());
        transaksiController.insertTransaksi(tanggal, akun, jenis, kategori, jumlah, catatan, selectedJenisTransaksi);
    }//GEN-LAST:event_kirimButtonActionPerformed
//        String tanggal2 = tanggalTransaksi2.getText();
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kategoriTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriTransaksiActionPerformed

    private void jenisTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisTransaksiActionPerformed
        String selectedJenisTransaksi = (String) jenisTransaksi.getSelectedItem();
    
        if ("pemasukan".equals(selectedJenisTransaksi)) {
            kategoriTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bulanan", "bonus", "thr" }));
        } else if ("pengeluaran".equals(selectedJenisTransaksi)) {
            kategoriTransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "makan", "transportasi", "internet" }));
        }
    }//GEN-LAST:event_jenisTransaksiActionPerformed

    private void akunTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunTransaksiActionPerformed
        String selectedAkunTransaksi = (String) akunTransaksi.getSelectedItem();
        
        if("cash".equals(selectedAkunTransaksi)){
            jenisAkun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-"}));
        } else if("debit".equals(selectedAkunTransaksi)){
            jenisAkun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRI","BCA"}));
        } else if("emoney".equals(selectedAkunTransaksi)){
            jenisAkun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gopay","ovo","shopeepay"}));
        }
    }//GEN-LAST:event_akunTransaksiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> akunTransaksi;
    private javax.swing.JTextField catatanTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jenisAkun;
    private javax.swing.JComboBox<String> jenisTransaksi;
    private javax.swing.JTextField jumlahTransaksi;
    private javax.swing.JComboBox<String> kategoriTransaksi;
    private javax.swing.JButton kirimButton;
    private com.toedter.calendar.JDateChooser tanggalTransaksi;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
